Algoritmo "exercicio5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Média do aluno na disciplina
// Autor(a)    : Caroline Santos
// Data atual  : 18/08/2026
Var
   nota1, nota2, media: real
   
Inicio
      escreva ("Nota 1: ")
      leia (nota1)
      escreva ("Nota 2: ")
      leia (nota2)
      media <- (nota1 + nota2)/2
      escreva ("A média entre ", nota1, " e", nota2, " é igual a", media,".")
Fimalgoritmo