Algoritmo "exercicio4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Algoritmo que lê dois números e mostre o somatório entre eles
// Autor(a)    : Caroline Santos
// Data atual  : 18/08/2026

Var
   valor1, valor2, soma: inteiro
   
Inicio
      escreva ("Digite um valor: ")
      leia (valor1)
      escreva ("Digite outro valor: ")
      leia (valor2)
      soma <- valor1 + valor2
      escreva ("A soma entre ", valor1, " e", valor2, " é igual a", soma,".")

Fimalgoritmo