Algoritmo "exercicio13"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aumento de salário
// Autor(a)    : Caroline Santos
// Data atual  : 20/08/2026

Var
   salario, novo_salario: real
   
Inicio
      escreva("Qual o valor do seu salário: R$")
      leia(salario)
      novo_salario <- salario * 1.15
      escreval("Seu salário com 15% de aumento é de: R$", novo_salario:5:2)

Fimalgoritmo