Algoritmo "exercicio7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Dobro e a terça parte de um número real
// Autor(a)    : Caroline Santos
// Data atual  : 18/08/2026
Var
   num: real

Inicio
      escreva ("Digite um número: ")
      leia (num)
      escreval ("O dobro de",num, " é ", num * 2:1:1)
      escreval ("A terça parte de",num, " é ", num / 3:1:2)

Fimalgoritmo